version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5004
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5004:5004"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/family-budget
      - PORT=5004
      - CLIENT_URL=http://localhost:3000
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    user: root

volumes:
  mongodb_data:
  jenkins_home:
