name: CI/CD Pipeline

on:
  push:
    branches: [ "feature/fixed-expenses-dashboard" ]
  pull_request:
    branches: [ "feature/fixed-expenses-dashboard" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './front/package-lock.json'

    - name: Install Frontend Dependencies
      working-directory: ./front
      run: npm install

    - name: Build Frontend
      working-directory: ./front
      run: npm run build
      env:
        CI: false  # This prevents treating warnings as errors

    # Backend
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Backend Structure
      run: |
        if [ -d "backend" ]; then
          echo "Backend directory exists"
          ls -la backend/
        fi

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./front
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/family-budget-frontend:latest

    - name: Build and Push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/family-budget-backend:latest

    - name: Test Docker Compose Configuration
      run: docker compose config
        
    # Optional: Test the containers
    - name: Start Containers
      run: |
        docker compose up -d
        
    - name: Check Running Containers
      run: |
        docker compose ps
        sleep 30
        
    - name: Check Logs
      run: docker compose logs
        
    - name: Stop Containers
      run: docker compose downname: CI/CD Pipeline

on:
  push:
    branches: [ "feature/fixed-expenses-dashboard" ]
  pull_request:
    branches: [ "feature/fixed-expenses-dashboard" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './front/package-lock.json'

    - name: Install Frontend Dependencies
      working-directory: ./front
      run: npm install

    - name: Build Frontend
      working-directory: ./front
      run: npm run build
      env:
        CI: false  # This prevents treating warnings as errors

    # Backend
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Backend Structure
      run: |
        if [ -d "backend" ]; then
          echo "Backend directory exists"
          ls -la backend/
        fi

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./front
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/family-budget-frontend:latest

    - name: Build and Push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/family-budget-backend:latest

    - name: Test Docker Compose Configuration
      run: docker compose config
        
    # Optional: Test the containers
    - name: Start Containers
      run: |
        docker compose up -d
        
    - name: Check Running Containers
      run: |
        docker compose ps
        sleep 30
        
    - name: Check Logs
      run: docker compose logs
        
    - name: Stop Containers
      run: docker compose down