name: CI/CD Pipeline

on:
  push:
    branches: [ "feature/fixed-expenses-dashboard" ]
  pull_request:
    branches: [ "feature/fixed-expenses-dashboard" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './front/package-lock.json'

    - name: Install Frontend Dependencies
      working-directory: ./front
      run: |
        if [ -f "package.json" ]; then
          npm ci || npm install
        else
          echo "No package.json found, skipping frontend dependencies"
        fi

    - name: Build Frontend
      working-directory: ./front
      run: |
        if [ -f "package.json" ]; then
          npm run build || echo "Build script not found, skipping build"
        else
          echo "No package.json found, skipping build"
        fi

    - name: Test Frontend
      working-directory: ./front
      run: npm test
      continue-on-error: true  # אם אין טסטים עדיין, זה לא יכשיל את ה-workflow

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Backend Dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Run Backend Tests
      run: |
        if [ -d tests ]; then
          python -m pytest
        else
          echo "No tests directory found, skipping backend tests"
        fi
      continue-on-error: true  # אם אין טסטים עדיין, זה לא יכשיל את ה-workflow

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        if [ -f "docker-compose.yml" ]; then
          docker compose build
        else
          echo "No docker-compose.yml found, skipping Docker build"
        fi
